name: hotfix-helper
on:
  schedule:
    - cron: "* * * * *"

jobs:
  merge-pr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/setup-node@v1
        with:
          version: 12
      - run: npm install --registry=https://registry.npmjs.org @actions/github
      - run: npm install --registry=https://registry.npmjs.org @actions/core
      - run: node -e 'require("./.github/actions/auto-pr-and-merge").autoMergePr()'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
