name: block-merge-to-broken-branch
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited

jobs:
  block-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          version: 12
      - run: npm install @octokit/action
      - run: npm install @actions/core
      - run: node .github/actions/block-merge-to-broken-branch.js
      - run: apt install tree
      - run: tree
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}