name: DDL Upgrade
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run ddl against'
        type: environment
        required: true 

jobs:
  test-env:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      SEC: ${{ secrets.SEC }}
    steps:
      - name: echo SEC
        run: |
          echo ${SEC:2:6}
      - name: echo env
        run: |
          echo "input is: ${{ inputs.environment}}"
          echo "gh input is: ${{ github.event.inputs.environment}}"
          echo "ESC is: ${SEC:2:5}"

      