name: DDL Upgrade
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run ddl against'
        type: environment
        required: true 

jobs:
  test-env:
    runs-on: ubuntu-latest
    env:
      SEC: ${{ secerts.SEC }}
    steps:
      - name: echo
        run: |
          echo ${SEC:0:5}


      