name: pr-target-branch-broken-check
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          version: 12
      - run: npm install --registry=https://registry.npmjs.org @actions/github
      - run: npm install --registry=https://registry.npmjs.org @actions/core
      - run: node .github/actions/block-merge-to-broken-branch.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
